E-Commerce-Playground/Controllers/AdminController.cs
using E_Commerce_Playground.Data;
using E_Commerce_Playground.Models;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Drawing.Text;

namespace E_Commerce_Playground.Controllers
{
    public class AdminController : Controller
    {

        private readonly AppDbContext _context;
        static int TotalUsers { get; set; }
        static int TotalProducts { get; set; }
        static int TotalStores { get; set; }
        private List<int> totals { get; set; }

       
        public AdminController(AppDbContext context) 
        {
            totals = new List<int>();
        _context= context;

            TotalProducts = _context.Products.Count();
            TotalUsers = _context.Users.Count();
            TotalStores = _context.Stores.Count();
            totals.Add(TotalUsers);
            totals.Add(TotalProducts);
            totals.Add(TotalStores);
        
        
        }

        public static int GetUsers()
        {
            return TotalUsers;
        }
        public static int GetStores()
        {
            return TotalStores;
        }
        public static int GetProducts()
        {
            return TotalProducts;
        }
        public IActionResult Index()
        {

            var totaldata = GetUsers();
            
            return View();
        }


        public IActionResult Users()
        { var data = _context.Users.ToList();
            return View(data);
        }

    }
}

E-Commerce-Playground/Controllers/LoginnController.cs
using E_Commerce_Playground.Data;
using E_Commerce_Playground.Models;
using E_Commerce_Playground.Controllers;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.ChangeTracking;
using Microsoft.IdentityModel.Tokens;
using System;
using System.ComponentModel.DataAnnotations;
using System.Net.Http;
using System.Security.Claims;

namespace E_Commerce_Playground.Controllers
{
    public class LoginnController : Controller
    {
        private readonly AppDbContext _context;




        public LoginnController(AppDbContext context)
        {
            _context = context;


        }

        public IActionResult Index()
        {
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Login(User user)
        {
            var input = user;
            var data = _context.Users.ToList();
            foreach (var item in data)
            {
                if (item.UserName.Contains(input.UserName) && item.Password.Contains(input.Password))
                {


                    var options = new CookieOptions();

                    options.IsEssential = true;
                    options.Expires = DateTimeOffset.UtcNow.AddMinutes(30);
                    options.Secure = true;

                    if (item.AccountLevel == 0)
                    {
                        
                        HttpContext.Response.Cookies.Append("MyCookie", $"{input.UserName}", options);
                        HttpContext.Response.Cookies.Append("Level", $"{item.AccountLevel}", options);
                   
                       
                    }
                    else
                    {
                        HttpContext.Response.Cookies.Append("MyCookie", $"{input.UserName}", options);
                    }


                    return RedirectToAction("Index","Home");
                    
                }
                return RedirectToAction("Index");
            }


            return RedirectToAction("Redirect");


        }

       

       


        public IActionResult Redirect()
        {
            return View();
        }


        public IActionResult Logout()
        {
            var options = new CookieOptions();
          

            HttpContext.Response.Cookies.Delete("MyCookie", options);
            return Index();
        }



    }

}

   

E-Commerce-Playground/Controllers/ProductsController.cs
using E_Commerce_Playground.Data;
using Microsoft.AspNetCore.Mvc;

namespace E_Commerce_Playground.Controllers
{
    public class ProductsController : Controller
    {
        private readonly AppDbContext _context;

        public ProductsController(AppDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            var data = _context.Products.ToList();

            return View(data);
        }


    }
}

E-Commerce-Playground/Controllers/ProfileController.cs
using E_Commerce_Playground.Data;
using Microsoft.AspNetCore.Mvc;

namespace E_Commerce_Playground.Controllers
{
    public class ProfileController : Controller
    {
        private readonly AppDbContext _context;

        public ProfileController(AppDbContext context)
        {
            _context= context;

        }


        public IActionResult Index()
        {

            var data = _context.Users.ToList();
            return View(data);
        }
    }
}

E-Commerce-Playground/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - E_Commerce_Playground</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/E_Commerce_Playground.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">

                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">E_Commerce_Playground</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @inject IHttpContextAccessor httpContext
                        @model IEnumerable<User>

                        @{
                            if (httpContext.HttpContext.Request.Cookies.ContainsKey("Level"))
                            {
                                var cookie = httpContext.HttpContext.Request.Cookies["Level"];

                                if (cookie.Contains("0"))
                                {
                                    <li class="nav-item">
                                        <a class="nav-link text-black" asp-area="" asp-controller="Admin" asp-action="Index">Admin</a>

                                    </li>
                                }
                            }
                        }











                        <li class="nav-item">
                            <a class="nav-link text-black" asp-area="" asp-controller="Loginn" asp-action="Logout">Logout</a>

                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Profile" asp-action="Index"> Profile</a>
                        </li>
                        
                        
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Products" asp-action="Index">Products</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Loginn" asp-action="Index"> Login</a>
                        </li>

                    </ul>
                    <a class="btn-lg text-dark" asp-area="" asp-controller="Loginn" asp-action="Logout">Logout</a>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - E_Commerce_Playground - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>